"""fix email_verification_codes code column to string 64

Revision ID: 87adf1e0d286
Revises: d93d1bbbc4ef
Create Date: 2026-04-06 02:51:51.770514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87adf1e0d286'
down_revision: Union[str, Sequence[str], None] = 'd93d1bbbc4ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_verification_codes', 'code',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_verification_codes', 'code',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
    # ### end Alembic commands ###
