"""create submissions table

Revision ID: a71dc2d172d6
Revises: c5905297e755
Create Date: 2026-04-08 16:39:21.083998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a71dc2d172d6'
down_revision: Union[str, Sequence[str], None] = 'c5905297e755'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('code_content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'REVIEW_REQUESTED', 'IN_REVIEW', 'COMPLETED', 'REJECTED', name='submissionstatus'), nullable=False),
    sa.Column('submitter_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_id'), 'submissions', ['id'], unique=False)
    op.create_index(op.f('ix_submissions_title'), 'submissions', ['title'], unique=False)
    op.drop_index(op.f('ix_reveiwer_skills_profile_id'), table_name='reviewer_skills')
    op.create_index(op.f('ix_reviewer_skills_profile_id'), 'reviewer_skills', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviewer_skills_profile_id'), table_name='reviewer_skills')
    op.create_index(op.f('ix_reveiwer_skills_profile_id'), 'reviewer_skills', ['profile_id'], unique=False)
    op.drop_index(op.f('ix_submissions_title'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_id'), table_name='submissions')
    op.drop_table('submissions')
    # ### end Alembic commands ###
